# Configuration documentation: https://docs.helix-editor.com/master/configuration.html
  
theme = "gruvbox"

[editor]
scrolloff = 5
mouse = true
middle-click-paste = false
scroll-lines = 3
shell = ["sh", "-c"]
line-number = "relative"
cursorline = false
cursorcolumn = false
gutters = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]
auto-completion = true
auto-format = true
auto-save = false
idle-timeout = 400
completion-trigger-len = 2
auto-info = true
true-color = false
rulers = []
bufferline = "never"
color-modes = false
auto-pairs = true

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right  = ["diagnostics", "selections", "position", "file-encoding"]
separator = "|"
mode.normal = "NOR"
mode.insert = "INS"
mode.select = "SEL"

[editor.lsp]
display-messages = false
auto-signature-help = true
display-signature-help-docs = true

[editor.cursor-shape]
normal = "block"
insert = "block"
select = "block"

[editor.file-picker]
hidden = true
parents = true
ignore = true
git-ignore = true
git-global = true
git-exclude = true

[editor.search]
smart-case = true
wrap-around = true